### ISSUE TITLE
`ValueError: could not convert string to float: ''` when using `.to_netcdf()`

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [oceanmodeling/StormEvents#25]
```python
from datetime import timedelta

from shapely.geometry import box

from stormevents import StormEvent

storm = StormEvent('irma', 2017,  start_date='2017-09-01 00:00:00', end_date='2017-09-12 00:00:00')

print(f'irma start: {storm.start_date}')
print(f'irma end: {storm.end_date}')

track = storm.track()
bnd = track.linestring.bounds

print(f'irma track bounds: {bnd}')

water_levels = storm.coops_product_within_region(product='water_level', region=box(*bnd))

water_levels.to_netcdf('irma_water_levels.nc')
```
```
irma start: 2017-09-01 00:00:00
irma end: 2017-09-12 00:00:00
/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/pandas/core/indexing.py:2108: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  new_ix = Index(new_ix)
/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/pandas/core/indexing.py:2108: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  new_ix = Index(new_ix)
irma track bounds: (-84.4, 16.6, -35.1, 31.9)
Traceback (most recent call last):
  File "/home/zrb/.config/JetBrains/PyCharmCE2021.3/scratches/storms/florence2018/coops.py", line 19, in <module>
    water_levels.to_netcdf('irma_water_levels.nc')
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/core/dataset.py", line 1901, in to_netcdf
    return to_netcdf(
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/backends/api.py", line 1072, in to_netcdf
    dump_to_store(
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/backends/api.py", line 1119, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/backends/common.py", line 261, in store
    variables, attributes = self.encode(variables, attributes)
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/backends/common.py", line 350, in encode
    variables, attributes = cf_encoder(variables, attributes)
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/conventions.py", line 859, in cf_encoder
    new_vars = {k: encode_cf_variable(v, name=k) for k, v in variables.items()}
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/conventions.py", line 859, in <dictcomp>
    new_vars = {k: encode_cf_variable(v, name=k) for k, v in variables.items()}
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/conventions.py", line 279, in encode_cf_variable
    var = ensure_dtype_not_object(var, name=name)
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/conventions.py", line 234, in ensure_dtype_not_object
    data = _copy_with_dtype(data, dtype=inferred_dtype)
  File "/home/zrb/environments/StormEvents_39/lib/python3.9/site-packages/xarray/conventions.py", line 195, in _copy_with_dtype
    result[...] = data
ValueError: could not convert string to float: ''

Process finished with exit code 1
```

**Comment by zacharyburnettNOAA** [comment]
it seems that the issue is with the data type of the variable arrays being `object` instead of `float64` or `string` 
```
<xarray.Dataset>
Dimensions:  (t: 2641, nos_id: 31)
Coordinates:
  * t        (t) datetime64[ns] 2017-09-01 2017-09-01T00:06:00 ... 2017-09-12
  * nos_id   (nos_id) int64 8720030 8720218 8720219 ... 9759110 9759394 9759938
    nws_id   (nos_id) <U5 'FRDF1' 'MYPF1' 'DMSF1' ... 'MGIP4' 'MGZP4' 'MISP4'
    x        (nos_id) float64 -81.44 -81.44 -81.56 ... -67.06 -67.19 -67.94
    y        (nos_id) float64 30.67 30.39 30.39 30.31 ... 17.97 18.22 18.09
Data variables:
    v        (nos_id, t) object 1.99399995803833 ... 8.937999725341797
    s        (nos_id, t) object 0.012000000104308128 ... 0.032999999821186066
    f        (nos_id, t) object '0,0,0,0' '0,0,0,0' ... '0,0,0,0' '0,0,0,0'
    q        (nos_id, t) object 'v' 'v' 'v' 'v' 'v' 'v' ... 'v' 'v' 'v' 'v' 'v'
```
